version: '3.4'

services:

  users:
    container_name: users
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    expose:
      - "5000"
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@users-db:5432/users_test
      # create a .env in root folder if it doesn't already exist
      # add the the following
      # SECRET_KEY=enter_secret_key_here
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - users-db
    links:
      - users-db


  users-db:
    container_name: users-db
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - "5432"
    environment:
      # create a .env in root folder if it doesn't already exist
      # POSTGRES_USER=enter_user_name_here
      # POSTGRES_PASSWORD=enter_secure_password_here
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client


  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    ports:
      - 3007:80
    depends_on:
      - users
    links:
      - users
