FROM python:3.6

# install environment dependencies
RUN apt-get --allow-unauthenticated update -yqq && apt-get --allow-unauthenticated install -yqq --no-install-recommends netcat && apt-get -q clean

# set working directory
RUN mkdir -p /app

# add requirements file first so we can use cached
COPY requirements.txt ./app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

# add folder
COPY . /app

# Change permissions /app folder
RUN chmod 755 /app

# entry point
RUN chmod 777 ./entrypoint-prod.sh

# run server
CMD ["./entrypoint-prod.sh"]

