FROM python:3.6

# install environment dependencies
RUN apt-get update -yqq && apt-get install -yqq --no-install-recommends netcat && apt-get -q clean

# set working directory
RUN mkdir -p /app
WORKDIR /app

# add folder
ADD . /app

# install requirements
RUN pip install -r requirements.txt

# entry point
RUN chmod 777 ./entrypoint-prod.sh

# run server
CMD ["./entrypoint-prod.sh"]

