# build environment
FROM node:10 as builder

# make directory
RUN mkdir -p /app

# set working directory
WORKDIR /app


# copy package.json
COPY yarn.lock /app/yarn.lock
COPY package.json /app/package.json

# install node packages
RUN yarn install --pure-lockfile

# COPY folder
COPY . /app

# add */node_modules/.bin to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add ARG instructions
ARG REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV

# set ENV
ENV NODE_ENV $NODE_ENV
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL

# run build
RUN yarn run build

# production  environment
FROM  nginx:1.15

# update nginx conf
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

# copy static files
COPY  --from=builder  /app/build  /usr/share/nginx/html

# expose port
EXPOSE  80
CMD ["nginx", "-g", "daemon off;"]
