# base image
FROM node:8.11

# set working directory
RUN mkdir -p /app
WORKDIR /app

# add folder
ADD . /app

# add */node_modules/.bin to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
RUN npm install --silent
RUN npm install react-scripts@1.1.4 -g --silent

# start app
CMD ["npm", "start"]
