# base image
FROM node:10

# set working directory
WORKDIR /app

# Make directory
RUN mkdir -p /app

# add folder
ADD . /app

# add */node_modules/.bin to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
RUN yarn install && yarn cache clean

# start app
CMD ["yarn", "start"]
