# build environment
FROM node:10 as builder

# make directory
RUN mkdir /app

# set working directory
WORKDIR /app

# add */node_modules/.bin to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add ARG instructions
ARG REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV

# set ENV
ENV NODE_ENV $NODE_ENV
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL

# copy package.json
COPY package.json /app/package.json

# install node packages
RUN yarn install

# COPY folder
COPY . /app

# run build
RUN yarn run build

# production  environment
FROM  nginx:1.15
COPY  --from=builder  /app/build  /usr/share/nginx/html
EXPOSE  80
CMD ["nginx", "-g", "daemon off;"]
